version: '3'
services:
  nginx:
    image: buterbrodskij/lemp:amd64
    ports:
      - 6666:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./html:/var/www/html
    depends_on:
      - php
    networks:
      - backend
      - frontend

  php:
    image: buterbrodskij/lemp:amd64
    volumes:
      - ./html:/var/www/html
    networks:
      - backend

  mysql:
    image: buterbrodskij/lemp:amd64
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: buterbrodskij/lemp:amd64
    ports:
      - 6001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:

