name: Build and Push Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            context: nginx
            image: buterbrodskij/nginx
          - dockerfile: ./Dockerfile
            context: html
            image: buterbrodskij/html
          - dockerfile: ./Dockerfile
            context: mysql
            image: buterbrodskij/mysql

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ matrix.context }}"
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}